### ISSUE TITLE
コメントアウトされたコードが残っている

### ISSUE THREAD

**Issue by fumiya-kume** [lv7777/telma_client#4]
https://github.com/lv7777/telma_client/blob/master/www/js/login.js
:-)

**Comment by lv7777** [comment]
俺のコードじゃないからあまり下手に触りたくないんだよなー
まだ俺も全部把握してるわけじゃないし・・・

レグレッションバグを避けるためにリファクタリングは大体の構造とonsen uiのアーキテクチャを理解してからのほうがいいと思われます。

**Comment by lv7777** [comment]
ということでclosed
